apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-node-firefox
  namespace: selenium-grid
  labels:
    name: selenium-node-firefox
spec:
  replicas: 2
  selector:
    name: selenium-node-firefox
  template:
    metadata:
      labels:
        name: selenium-node-firefox
    spec:
      containers:
      - name: selenium-node-firefox
        image: selenium/node-firefox:3.14.0-arsenic
        ports:
          - containerPort: 5900
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
        resources:
          limits:
            memory: "8Gi"
      containers:
      - name: selenium-node-firefox2
        image: selenium/node-firefox:3.14.0-arsenic
        ports:
          - containerPort: 5901
        env:
          - name: HUB_PORT_4444_TCP_ADDR
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT
            value: "4444"
        resources:
          limits:
            memory: "8Gi"
