apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub
  namespace: selenium-grid
  labels:
    name: selenium-hub
spec:
  replicas: 1
  selector:
    name: selenium-hub
  template:
    metadata:
      labels:
        name: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:3.14.0-arsenic
        ports:
          - containerPort: 4444
        resources:
          limits:
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /grid/console
            port: 4444
          initialDelaySeconds: 30
          timeoutSeconds: 5